export const endpoints = {
  authRegister: '/auth/register',
  authLogin: '/auth/login',
  authVerifyOtp: '/auth/verify-otp',
  authProfile: '/auth/profile',
  authPassword: '/auth/password',
  authAdminResetPassword: '/admin/reset-password',
  customers: '/customers',
  customersMeasurements: (customerId: string) => `/customers/${customerId}/measurements`,
  measurementById: (measurementId: string) => `/measurements/${measurementId}`,
  measurementCreateJob: (measurementId: string) => `/measurements/${measurementId}/create-job`,
  jobs: '/jobs',
  jobById: (jobId: string) => `/jobs/${jobId}`,
  dashboard: '/dashboard',
} as const
